apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-hello
  template:
    metadata:
      labels:
        app: backend-hello
    spec:
      containers:
      - name: backend-hello
        image: flowerking21/micro_backend_helloservice:latest
        ports:
        - containerPort: 4200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-profile
  template:
    metadata:
      labels:
        app: backend-profile
    spec:
      containers:
      - name: backend-profile
        image: flowerking21/micro_backend_profileservice:latest
        ports:
        - containerPort: 4201
      
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: flowerking21/micro_frontendservice:latest
        ports:
        - containerPort: 3000



